INSERT INTO ventana VALUES (1, 1, NULL, 'Menú Marca', 'marcas.jsp');
INSERT INTO ventana VALUES (6, 1, NULL, 'Menú Expediente', 'expedientes.jsp');
INSERT INTO ventana VALUES (21, 1, NULL, 'Menú Agente', 'abogados.jsp');
INSERT INTO ventana VALUES (26, 1, NULL, 'Menú Titular', 'clientes.jsp');
INSERT INTO ventana VALUES (31, 1, NULL, 'Menú Usuario', 'usuarios.jsp');
INSERT INTO ventana VALUES (36, 1, NULL, 'Menú Rol', 'roles.jsp');
INSERT INTO ventana VALUES (40, 1, NULL, 'Menú Permiso', 'permisos.jsp');
INSERT INTO ventana VALUES (9, 3, 8, 'Menú Documento', 'documentos.jsp');
INSERT INTO ventana VALUES (14, 3, 8, 'Menú Evento', 'eventos.jsp');
INSERT INTO ventana VALUES (22, 2, 21, 'Agregar Agente', 'agregarAbogado.jsp');
INSERT INTO ventana VALUES (23, 2, 21, 'Ver Agente', 'verAbogado.jsp');
INSERT INTO ventana VALUES (24, 2, 21, 'Editar Agente', 'editarAbogado.jsp');
INSERT INTO ventana VALUES (25, 2, 21, 'Eliminar Agente', 'eliminarAbogado');
INSERT INTO ventana VALUES (27, 2, 26, 'Agregar Titular', 'agregarCliente.jsp');
INSERT INTO ventana VALUES (28, 2, 26, 'Ver Titular', 'verCliente.jsp');
INSERT INTO ventana VALUES (29, 2, 26, 'Editar Titular', 'editarCliente.jsp');
INSERT INTO ventana VALUES (30, 2, 26, 'Eliminar Titular', 'eliminarCliente');
INSERT INTO ventana VALUES (10, 4, 9, 'Agregar Documento', 'agregarDocumento.jsp');
INSERT INTO ventana VALUES (11, 4, 9, 'Ver Documento', 'verDocumento.jsp');
INSERT INTO ventana VALUES (12, 4, 9, 'Editar Documento', 'editarDocumento.jsp');
INSERT INTO ventana VALUES (13, 4, 9, 'Eliminar Documento', 'eliminarDocumento');
INSERT INTO ventana VALUES (15, 4, 14, 'Agregar Evento', 'agregarEvento.jsp');
INSERT INTO ventana VALUES (16, 4, 14, 'Ver Evento', 'verEvento.jsp');
INSERT INTO ventana VALUES (17, 4, 14, 'Editar Evento', 'editarEvento.jsp');
INSERT INTO ventana VALUES (18, 4, 14, 'Eliminar Evento', 'eliminarEvento');
INSERT INTO ventana VALUES (7, 2, 6, 'Agregar Expediente', 'agregarExpediente.jsp');
INSERT INTO ventana VALUES (8, 2, 6, 'Ver Expediente', 'verExpediente.jsp');
INSERT INTO ventana VALUES (19, 2, 6, 'Editar Expediente', 'editarExpediente.jsp');
INSERT INTO ventana VALUES (20, 2, 6, 'Eliminar Expediente', 'eliminarExpediente');
INSERT INTO ventana VALUES (2, 2, 1, 'Agregar Marca', 'agregarMarca.jsp');
INSERT INTO ventana VALUES (3, 2, 1, 'Ver Marca', 'verMarca.jsp');
INSERT INTO ventana VALUES (4, 2, 1, 'Editar Marca', 'editarMarca.jsp');
INSERT INTO ventana VALUES (5, 2, 1, 'Eliminar Marca', 'eliminarMarca');
INSERT INTO ventana VALUES (42, 2, 40, 'Ver Permiso', 'verPermiso.jsp');
INSERT INTO ventana VALUES (41, 2, 40, 'Editar Permiso', 'editarPermiso.jsp');
INSERT INTO ventana VALUES (37, 2, 36, 'Agregar Rol', 'agregarRol.jsp');
INSERT INTO ventana VALUES (38, 2, 36, 'Editar Rol', 'editarRol.jsp');
INSERT INTO ventana VALUES (39, 2, 36, 'Eliminar Rol', 'eliminarRol');
INSERT INTO ventana VALUES (32, 2, 31, 'Agregar Usuario', 'agregarUsuario.jsp');
INSERT INTO ventana VALUES (33, 2, 31, 'Ver Usuario', 'verUsuario.jsp');
INSERT INTO ventana VALUES (34, 2, 31, 'Editar Usuario', 'editarUsuario.jsp');
INSERT INTO ventana VALUES (35, 2, 31, 'Eliminar Usuario', 'eliminarUsuario');
INSERT INTO ventana VALUES (43, 2, 36, 'Ver Rol', 'verRol.jsp');
INSERT INTO ventana VALUES (76, 1, NULL, 'Menu Prefijo', 'prefijos.jsp');
INSERT INTO ventana VALUES (69, 1, NULL, 'Menú Facturas', 'facturas.jsp');
INSERT INTO ventana VALUES (77, 1, NULL, 'Menu Facturacion', 'facturaciones.jsp');
INSERT INTO ventana VALUES (44, 3, 8, 'Oposiciones Recibidas', 'oposicionesRecibidas.jsp');
INSERT INTO ventana VALUES (45, 4, 44, 'Agregar oposición recibida', 'agregarOposicionRecibida.jsp');
INSERT INTO ventana VALUES (46, 4, 44, 'Ver oposición recibida', 'verOposicionRecibida.jsp');
INSERT INTO ventana VALUES (47, 4, 44, 'Editar oposición recibida', 'editarOposicionRecibida.jsp');
INSERT INTO ventana VALUES (48, 4, 44, 'Eliminar oposicion recibida', 'eliminarOposicionRecibida');
INSERT INTO ventana VALUES (49, 1, NULL, 'Menú Oposiciones Hechas', 'oposicionesHechas.jsp');
INSERT INTO ventana VALUES (50, 1, NULL, 'Configuraciones', 'configuraciones.jsp');
INSERT INTO ventana VALUES (53, 49, NULL, 'Agregar Oposiciones Hechas', 'agregarOposicionHecha.jsp');
INSERT INTO ventana VALUES (54, 49, NULL, 'Ver Oposiciones Hechas', 'verOposicionHecha.jsp');
INSERT INTO ventana VALUES (55, 49, NULL, 'Editar Oposicion Hecha', 'editarOposicionHecha.jsp');
INSERT INTO ventana VALUES (56, 49, NULL, 'Eliminar Oposicion Hecha', 'eliminarOposicionHecha');
INSERT INTO ventana VALUES (57, 54, NULL, 'Menu Documento Oposiciones Hechas', 'documentosOposicionesHechas.jsp');
INSERT INTO ventana VALUES (58, 54, NULL, 'Menu Evento Oposiciones Hechas', 'eventosOposicionesHechas.jsp');
INSERT INTO ventana VALUES (59, 58, NULL, 'Agregar Evento OH', 'agregarEventoOposicionHecha.jsp');
INSERT INTO ventana VALUES (60, 58, NULL, 'Ver Evento de Oposiciones H', 'verEventoOposicionHecha.jsp');
INSERT INTO ventana VALUES (61, 58, NULL, 'Editar Evento Oposiciones Hechas', 'editarEventoOposicionHecha.jsp');
INSERT INTO ventana VALUES (62, 58, NULL, 'Eliminar Evento Oposicion Hechas', 'eliminarEventoOposicionHecha');
INSERT INTO ventana VALUES (63, 54, NULL, 'Agregar Doc', 'agregarDocumentoOposicionHecha.jsp');
INSERT INTO ventana VALUES (64, 54, NULL, 'Ver doc', 'verDocumentoOposicionHecha.jsp');
INSERT INTO ventana VALUES (68, 54, NULL, 'Eliminar', 'eliminarDocumentoOposicionHecha');
INSERT INTO ventana VALUES (67, 54, NULL, 'Editar doc', 'editarDocumentoOposicionHecha.jsp');
INSERT INTO ventana VALUES (70, 1, NULL, 'notificaciones', 'notificaciones.jsp');
INSERT INTO ventana VALUES (72, 69, NULL, 'verFactura', 'verFactura.jsp');
INSERT INTO ventana VALUES (73, 69, NULL, 'anularFactura', 'anularFactura.jsp');
INSERT INTO ventana VALUES (71, 69, NULL, 'agregar factura', 'agregarFactura.jsp');
INSERT INTO ventana VALUES (74, 1, NULL, 'ver prefijo', 'verPrefijo.jsp');
INSERT INTO ventana VALUES (75, 1, NULL, 'editar prefijo', 'editarPrefijo.jsp');
